# destination: KP (perlis), PL (langkawi), KK (kedah)
# date: yyyy-mm-dd
mail:
  from: example@gmail.com
  to: example@gmail.com
  smtp: # nodemailer
    host: smtp.gmail.com
    port: 587
    secure: false
    auth:
      user: example@gmail.com
      pass: pass

watch:
  - enabled: true
    date: 2023-12-16
    from: KP
    to: PL
    condition:
      between:
        # start and end in format  07:30 pm
        start: 12:00 pm
        end: 06:00 pm
